### ISSUE TITLE
run least-cost paths on networks: raster vs triangulated

### ISSUE THREAD

**Issue by dgrimsman** [dgrimsman/boot-camp#3]
See [`run_routing()`](https://github.com/bbest/consmap/blob/master/server.R#L24-L91), particularly [`gdistance::shortestPath`](http://www.rdocumentation.org/packages/gdistance/versions/1.1-9/topics/shortestPath):

``` r
      # calculate shortest path
      rt = shortestPath(
        geoCorrection(transition(1 / (r1 + xt), mean, directions=8), type="c"), 
        xy[1],
        xy[2],
        output='SpatialLines')
```

**Comment by dgrimsman** [comment]
Okay, so I have the shortest path working for the triangulated graph. In order to compare, though, how do you calculate the distances in the raster? Do you assume the coordinates are planar or do you sit them on a sphere?

**Comment by dgrimsman** [comment]
Also, FYI, the shortest path algorithm that is begin used is Dijkstra's. I could not find an A\* implementation in R. Any suggestions on this? If not, I can try using python.

**Comment by bbest** [comment]
Good one @dgrimsman! Can you git commit and push so I can see?

To compare the triangulated with the the raster equivalent (just Euclidean distance, not whale risk weighted yet), here's what I did in [bbest/consmap](https://github.com/bbest/consmap):
1. convert the `whales` raster in `index.Rmd` to having all values of 1, like https://github.com/bbest/consmap/blob/master/global.R#L208-L210:
   
   ``` r
   # ones map for getting linear path
   r1 = r
   r1[!is.na(r)] = 1
   ```
2. then run like https://github.com/bbest/consmap/blob/master/server.R#L47-L54 except you're not adding the whale resistance transformed (`xt`):
   
   ``` r
     # calculate shortest path
     rt = shortestPath(
       geoCorrection(transition(1 / (r1), mean, directions=8), type="c"), 
       xy[1],
       xy[2],
       output='SpatialLines')
   ```

**Comment by dgrimsman** [comment]
In 2 above, in what format are xy[1] and xy[2]? I know they're SpatialPoints objects but I am giving them values like [-13774791 6359667]. Does that seem right? The shortestPath function throws an error, basically saying that there is no path between the points that I have chosen. I will push in a few minutes so you can see.

**Comment by bbest** [comment]
Yep, per the documentation on [`gdistance::shortestPath`](http://www.rdocumentation.org/packages/gdistance/versions/1.1-9/topics/shortestPath), the origin and goal arguments can simply be the coordinates as a vector, eg `c(-13774791, 6359667)` (see also code in the Examples),  or other more complex objects like SpatialPoints or matrix:

> - **origin**: SpatialPoints, vector or matrix with coordinates, at the moment only the first cell is taken into account
> - **goal**: SpatialPoints, vector or matrix with coordinates
